codecov:
  branch: develop
  bot: appknox-bot

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: '70'
        threshold: null
        branches: null

    patch: off

    changes: off

  ignore:
    - tests/.*

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: once
