version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}-
            - v1-deps-
      - run:
          name: NPM Install
          command: npm install
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Ember Test
          command: COVERAGE=true npm test
